---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hommer
  labels:
    app: hommer
spec:
  selector:
    matchLabels:
      app: hommer
  replicas: 1 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app: hommer
    spec:
      containers: 
      - name: hommer
        image: b4bz/homer:v23.09.1
        volumeMounts:
        - name: assets
          mountPath: /www/assets
        ports:
        - containerPort: 8080
      volumes:
      - name: assets
        configMap: 
          name: homer-config

---
apiVersion: v1
kind: Service
metadata:
  name: hommer-dashboard
spec:
  selector:
    app: hommer
  ports:
    - port: 82
      targetPort: 8080


