apiVersion: apps/v1
kind: Deployment
metadata:
  name: hommer
  labels:
    app: hommer
spec:
  selector:
    matchLabels:
      app: hommer
  replicas: 1 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app: hommer
    spec:
      volumes:
      - name: git-repo-volume
        emptyDir: {}

      - name: config-volume
        configMap:
          name: homer-config
     
      # Define init container
      initContainers:
      - name: git-cloner
        image: alpine/git:latest
        # FIX 1: Change 'commad' to 'command'
        command: ["git", "clone", "https://git.anpham.me/DurianLAB/Homepage-Dashboard.git", "/repo"]
        volumeMounts:
        - name: git-repo-volume
          # FIX 2: Change 'mountpath' to 'mountPath'
          mountPath: /repo

      containers:
      - name: hommer
        image: b4bz/homer:v23.09.1
        volumeMounts:
        - name: git-repo-volume
          mountPath: /assets 

        - name: config-volume
          mountPath: 
          - name: /www/assets
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hommer-dashboard
spec:
  selector:
    app: hommer
  ports:
    - port: 82
      targetPort: 8080